[package]
name = "starter-templates"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
askama.workspace = true
serde_json.workspace = true
time.workspace = true
starter-contracts.workspace = true
starter-domain.workspace = true

[dev-dependencies]
uuid.workspace = true
